apiVersion: v1
kind: ConfigMap
metadata:
  name: estoque-config
  namespace: oficina-estoque
data:
  POSTGRES_HOST: REPLACE_WITH_RDS_ENDPOINT
  ESTOQUE_EVENTS_TOPIC_ARN: REPLACE_WITH_EVENTS_TOPIC_ARN
  ESTOQUE_COMMANDS_QUEUE_URL: REPLACE_WITH_COMMANDS_QUEUE_URL
  ESTOQUE_CATALOG_EVENTS_QUEUE_URL: REPLACE_WITH_CATALOG_EVENTS_QUEUE_URL
